name: Go

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Check formatting
      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi # props https://github.com/digitalocean/godo/issues/393

    - name: Check building
      run: go build .
